### ISSUE TITLE
Adding table to existing synchronisation results in panic

### ISSUE THREAD

**Issue by mcrauwel** [planetscale/singer-tap#32]
In my test-environment I'm using `sysbench` tables `sbtest1-8`.

I configured my singer-tap to sync 2 tables `sbtest1` and `sbtest2`, the sync is working fine, this is the output of my `state.json` file:
```
➜  Stitch cat state/state-1685454236696.json | jq
{
  "bookmarks": {
    "sbtest1": {
      "shards": {
        "-": {
          "cursor": "CgEtEghtY3JhdXdlbBqMAU15U1FMNTYvNzAzODExNDktZTk4ZC0xMWVkLWFjYzYtYmU1MDU4YzkxMzMwOjEtMTY4OCw3MDU1NjQ2NC1lOThkLTExZWQtYTliYi03YWI3YjI4NzdmYmQ6MS0yNDY0LDc0MmMxNDAxLWU5OGQtMTFlZC1iZjVjLTIyZTUzZmM5ODk5NToxLTEyNzE1"
        }
      }
    },
    "sbtest2": {
      "shards": {
        "-": {
          "cursor": "CgEtEghtY3JhdXdlbBqMAU15U1FMNTYvNzAzODExNDktZTk4ZC0xMWVkLWFjYzYtYmU1MDU4YzkxMzMwOjEtMTY4OCw3MDU1NjQ2NC1lOThkLTExZWQtYTliYi03YWI3YjI4NzdmYmQ6MS0yNDY3LDc0MmMxNDAxLWU5OGQtMTFlZC1iZjVjLTIyZTUzZmM5ODk5NToxLTEyNzE1"
        }
      }
    }
  }
}
```
I'm now adding a 3rd table `sbtest3` and re-running my sync with the following command: 
```
./singer-tap --config source.json  --catalog schema.json --state $(ls -t state/state-*json | head -1) | ps-http-tap  --api-token $(cat access_token) --api-url https://api.eu-central-1.stitchdata.com
```

The sync starts and it sync the initial 2 tables, however when reaching the 3rd table it fail with a panic.
```
HTTP Tap : INFO : Server response status : "OK", message : "Batch accepted"
HTTP Tap : INFO : Published [100000] records for stream "sbtest2"
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/planetscale/singer-tap/cmd/internal.Sync.func2(0x14000b70ef0?)
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/internal/sync.go:98 +0x94
github.com/planetscale/singer-tap/cmd/internal.PlanetScaleEdgeDatabase.sync({{_, _}, {_, _}, _}, {_, _}, _, {_, _}, ...)
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/internal/planetscale_edge_database.go:230 +0x6a8
github.com/planetscale/singer-tap/cmd/internal.PlanetScaleEdgeDatabase.Read({{_, _}, {_, _}, _}, {_, _}, {{{0x140001b85d0, 0x16}, {0x140001a3a18, ...}, ...}, ...})
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/internal/planetscale_edge_database.go:108 +0x348
github.com/planetscale/singer-tap/cmd/internal.Sync({0x1033a2510, 0x140001a2000}, {0x1033a5c90, 0x140005241a0}, {0x1033a1200, 0x1400028b050}, {0x1033a62d0, 0x1400018f130}, {{0x140001b85d0, 0x16}, ...}, ...)
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/internal/sync.go:102 +0xa10
main.sync({0x1033a2510, 0x140001a2000}, {0x1033a62d0, 0x1400018f130?}, {{0x140001b85d0, 0x16}, {0x140001a3a18, 0x8}, {0x140001b85b8, 0x14}, ...}, ...)
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/singer-tap/main.go:154 +0x200
main.execute(0x0, {0x1033a62d0, 0x1400018f130}, {0x16d547736?, 0x3?}, {0x16d54774c, 0xb}, {0x16d547760, 0x1e}, {0x12b3bb888, ...}, ...)
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/singer-tap/main.go:142 +0x3a0
main.main()
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/singer-tap/main.go:88 +0x4b0
```

**Comment by mcrauwel** [comment]
to clarify it panic's when:
- sbtest1 is incremental, sbtest2 and sbtest3 are full sync
- sbtest1 and sbtest2 are incremental and sbtest3 is full sync

it works fine when all tables are configured for incremental sync

**Comment by mcrauwel** [comment]
panic when `sbtest2` is incremental and `sbtest3` is full 
```
PlanetScale Tap : INFO : [table: sbtest1, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] Finished reading all rows for table [sbtest1]
PlanetScale Tap : INFO : Stream "sbtest2" will be synced incrementally
PlanetScale Tap : INFO : known position is CgEtEghtY3JhdXdlbBqMAU15U1FMNTYvNzAzODExNDktZTk4ZC0xMWVkLWFjYzYtYmU1MDU4YzkxMzMwOjEtMTY4OCw3MDU1NjQ2NC1lOThkLTExZWQtYTliYi03YWI3YjI4NzdmYmQ6MS0yNTg1LDc0MmMxNDAxLWU5OGQtMTFlZC1iZjVjLTIyZTUzZmM5ODk5NToxLTE0ODM0
PlanetScale Tap : INFO : syncing rows from stream "sbtest2" from shard "-" at position [MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14834]
PlanetScale Tap : INFO : stream's known position is "MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14834"
PlanetScale Tap : INFO : [table: sbtest2, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] peeking to see if there's any new rows
HTTP Tap : INFO : saving state to path : state/state-1685525295691.json
PlanetScale Tap : INFO : [table: sbtest2, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] syncing rows with cursor [shard:"-" keyspace:"mcrauwel" position:"MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14834"]
PlanetScale Tap : INFO : [table: sbtest2, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] latest database position is [MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14872]
PlanetScale Tap : INFO : [table: sbtest2, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] Finished reading all rows for table [sbtest2]
PlanetScale Tap : INFO : known position is CgEtEghtY3JhdXdlbA==
PlanetScale Tap : INFO : syncing rows from stream "sbtest3" from shard "-" at position []
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] peeking to see if there's any new rows
HTTP Tap : INFO : saving state to path : state/state-1685525296127.json
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] syncing rows with cursor [shard:"-" keyspace:"mcrauwel"]
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] latest database position is [MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14873]
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/planetscale/singer-tap/cmd/internal.Sync.func2(0x14000374580?)
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/internal/sync.go:98 +0x94
github.com/planetscale/singer-tap/cmd/internal.PlanetScaleEdgeDatabase.sync({{_, _}, {_, _}, _}, {_, _}, _, {_, _}, ...)
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/internal/planetscale_edge_database.go:230 +0x6a8
github.com/planetscale/singer-tap/cmd/internal.PlanetScaleEdgeDatabase.Read({{_, _}, {_, _}, _}, {_, _}, {{{0x140002a63c0, 0x16}, {0x140002a44c8, ...}, ...}, ...})
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/internal/planetscale_edge_database.go:108 +0x348
github.com/planetscale/singer-tap/cmd/internal.Sync({0x105a16510, 0x1400003c090}, {0x105a19c90, 0x14000281a00}, {0x105a15200, 0x14000287440}, {0x105a1a2d0, 0x14000288280}, {{0x140002a63c0, 0x16}, ...}, ...)
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/internal/sync.go:102 +0xa10
main.sync({0x105a16510, 0x1400003c090}, {0x105a1a2d0, 0x14000288280?}, {{0x140002a63c0, 0x16}, {0x140002a44c8, 0x8}, {0x140002a63a8, 0x14}, ...}, ...)
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/singer-tap/main.go:154 +0x200
main.execute(0x0, {0x105a1a2d0, 0x14000288280}, {0x16aed3736?, 0x3?}, {0x16aed374c, 0xb}, {0x16aed3760, 0x1e}, {0x12da0b198, ...}, ...)
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/singer-tap/main.go:142 +0x3a0
main.main()
	/Users/mcrauwel/Workspace/PlanetScale/singer-tap/cmd/singer-tap/main.go:88 +0x4b0
```

**Comment by mcrauwel** [comment]
working fine when everything is incremental:

initial sync log
```
PlanetScale Tap : INFO : [table: sbtest2, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] Finished reading all rows for table [sbtest2]
PlanetScale Tap : INFO : Stream "sbtest3" will be synced incrementally
PlanetScale Tap : INFO : known position is CgEtEghtY3JhdXdlbA==
PlanetScale Tap : INFO : syncing rows from stream "sbtest3" from shard "-" at position []
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] peeking to see if there's any new rows
HTTP Tap : INFO : saving state to path : state/state-1685525409132.json
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] syncing rows with cursor [shard:"-" keyspace:"mcrauwel"]
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] latest database position is [MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14916]
HTTP Tap : INFO : flushing [9000] messages for stream "sbtest3" in [12] batches
...
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] Finished reading all rows for table [sbtest3]
HTTP Tap : INFO : saving state to path : state/state-1685525434991.json
HTTP Tap : INFO : saving state to path : state/state-1685525434993.json
HTTP Tap : INFO : Published [100000] records for stream "sbtest3"
HTTP Tap : INFO : flushing [1000] messages for stream "sbtest3" in [1] batches
HTTP Tap : INFO : Server response status : "OK", message : "Batch accepted"
```

incremental sync there after
```
PlanetScale Tap : INFO : Syncing records for PlanetScale database : mcrauwel
PlanetScale Tap : INFO : Stream "sbtest1" will be synced incrementally
PlanetScale Tap : INFO : known position is CgEtEghtY3JhdXdlbBqMAU15U1FMNTYvNzAzODExNDktZTk4ZC0xMWVkLWFjYzYtYmU1MDU4YzkxMzMwOjEtMTY4OCw3MDU1NjQ2NC1lOThkLTExZWQtYTliYi03YWI3YjI4NzdmYmQ6MS0yNTg1LDc0MmMxNDAxLWU5OGQtMTFlZC1iZjVjLTIyZTUzZmM5ODk5NToxLTE0OTEy
PlanetScale Tap : INFO : syncing rows from stream "sbtest1" from shard "-" at position [MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14912]
PlanetScale Tap : INFO : stream's known position is "MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14912"
PlanetScale Tap : INFO : [table: sbtest1, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] peeking to see if there's any new rows
PlanetScale Tap : INFO : [table: sbtest1, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] syncing rows with cursor [shard:"-" keyspace:"mcrauwel" position:"MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14912"]
PlanetScale Tap : INFO : [table: sbtest1, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] latest database position is [MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-15028]
PlanetScale Tap : INFO : [table: sbtest1, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] Finished reading all rows for table [sbtest1]
PlanetScale Tap : INFO : Stream "sbtest2" will be synced incrementally
PlanetScale Tap : INFO : known position is CgEtEghtY3JhdXdlbBqMAU15U1FMNTYvNzAzODExNDktZTk4ZC0xMWVkLWFjYzYtYmU1MDU4YzkxMzMwOjEtMTY4OCw3MDU1NjQ2NC1lOThkLTExZWQtYTliYi03YWI3YjI4NzdmYmQ6MS0yNTg1LDc0MmMxNDAxLWU5OGQtMTFlZC1iZjVjLTIyZTUzZmM5ODk5NToxLTE0OTE1
PlanetScale Tap : INFO : syncing rows from stream "sbtest2" from shard "-" at position [MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14915]
PlanetScale Tap : INFO : stream's known position is "MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14915"
PlanetScale Tap : INFO : [table: sbtest2, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] peeking to see if there's any new rows
HTTP Tap : INFO : saving state to path : state/state-1685525438243.json
PlanetScale Tap : INFO : [table: sbtest2, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] syncing rows with cursor [shard:"-" keyspace:"mcrauwel" position:"MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14915"]
PlanetScale Tap : INFO : [table: sbtest2, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] latest database position is [MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-15029]
PlanetScale Tap : INFO : [table: sbtest2, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] Finished reading all rows for table [sbtest2]
PlanetScale Tap : INFO : Stream "sbtest3" will be synced incrementally
PlanetScale Tap : INFO : known position is CgEtEghtY3JhdXdlbBqMAU15U1FMNTYvNzAzODExNDktZTk4ZC0xMWVkLWFjYzYtYmU1MDU4YzkxMzMwOjEtMTY4OCw3MDU1NjQ2NC1lOThkLTExZWQtYTliYi03YWI3YjI4NzdmYmQ6MS0yNTg1LDc0MmMxNDAxLWU5OGQtMTFlZC1iZjVjLTIyZTUzZmM5ODk5NToxLTE0OTE3
PlanetScale Tap : INFO : syncing rows from stream "sbtest3" from shard "-" at position [MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14917]
PlanetScale Tap : INFO : stream's known position is "MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14917"
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] peeking to see if there's any new rows
HTTP Tap : INFO : saving state to path : state/state-1685525438651.json
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] syncing rows with cursor [shard:"-" keyspace:"mcrauwel" position:"MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-14917"]
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] latest database position is [MySQL56/70381149-e98d-11ed-acc6-be5058c91330:1-1688,70556464-e98d-11ed-a9bb-7ab7b2877fbd:1-2585,742c1401-e98d-11ed-bf5c-22e53fc98995:1-15031]
PlanetScale Tap : INFO : [table: sbtest3, shard : -, tablet: primary, cells : [aws_euwest2a_1] ] Finished reading all rows for table [sbtest3]
HTTP Tap : INFO : saving state to path : state/state-1685525439041.json
HTTP Tap : INFO : saving state to path : state/state-1685525439041.json
```
